<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>https://github.com/c3m3gyanesh/p4-syntax-highlighter

Derived from various syntax definitaion files
      - c.tmLanguage
      - babel.tmLanguage
      - p4.vim 

Author  - Gyanesh Patra &lt;c3m3gyanesh@gmail.com&gt; 
Version - 1.0
Date    - 15 April 2016
&gt;&gt; With each modification, please update the date and version.

Still it needs a lot of imporvements.
Todo: 
  Numericals can be improved.
  Action, meter etc should be defined as function blocks.
  Updated with all entities missed from the specification.
  if/ifdef/endif
  And much more.....</string>
	<key>fileTypes</key>
	<array>
		<string>p4</string>
	</array>
	<key>name</key>
	<string>p4</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#p4-translation</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>define-directive</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(#)(define)(\s+[a-zA-Z_]\w*+)</string>
					<key>comment</key>
					<false/>
					<key>end</key>
					<string>(?&lt;=$\n)(?&lt;!\\$\n)</string>
					<key>name</key>
					<string>keyword.define.p4</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#p4-literal-number</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>include-header-directive</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(#)(include)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.include.start.p4</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>include headers</string>
					<key>end</key>
					<string>(?:("[^"]*?)|(&lt;[^&gt;]*?))(\n)|(?&lt;=$\n)(?&lt;!\\$\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.include.p4</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.lt-gt.include.p4</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.unexpected-end-of-line.p4</string>
						</dict>
					</dict>
					<key>name</key>
					<string>keyword.include.p4</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#include-header-directive-internals</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>include-header-directive-internals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#p4-preprocessor-lex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"|(?=.*?")</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.p4</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"|(?&lt;=^|[^\\])(?=\s*\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.p4</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.include.p4</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;(?=.*?&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.p4</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;|(?&lt;=^|[^\\])(?=\s*\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.p4</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.lt-gt.include.c</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)|(?&lt;=^|[^\\])(?=\s*\n)</string>
					<key>name</key>
					<string>meta.parens.c</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#include-header-directive-internals</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>lex-continuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.line-continuation.c</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.newline.c</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\)$(\n?)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.c</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.deprecated.space-after-continuation.c</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\\(\s+?)(?=\n)$</string>
				</dict>
			</array>
		</dict>
		<key>lex-newline</key>
		<dict>
			<key>match</key>
			<string>$\n</string>
			<key>name</key>
			<string>punctuation.whitespace.newline.c</string>
		</dict>
		<key>p4-abstractions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#p4-object-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-object-attribute-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-match-type-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-counter-type-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-todo</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-builtin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-primitives</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-conditional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-stateful</string>
				</dict>
			</array>
		</dict>
		<key>p4-builtin</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
\b
(apply|hit|miss
  |extract|set_metadata)
\b</string>
					<key>name</key>
					<string>keyword.builtin.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(/\*)</string>
					<key>end</key>
					<string>\s*(\*/)</string>
					<key>name</key>
					<string>comment.block.p4</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(//)</string>
					<key>end</key>
					<string>(?&lt;=$\n)(?&lt;!\\$\n)</string>
					<key>name</key>
					<string>comment.line.double.slash.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-conditional</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|select)\b</string>
					<key>name</key>
					<string>keyword.conditional.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>P4_PARSING_DONE</string>
					<key>name</key>
					<string>keyword.constants.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-counter-type-keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(bytes|packets)\b</string>
					<key>name</key>
					<string>keyword.counter.type.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-literal-number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(?:\B[-+]|\b)0x[0-9a-f]*\.(\B|\b[0-9]+)</string>
					<key>name</key>
					<string>invalid.illegal.numeric.hex.p4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:\B[-+]|\b)0[0-9]+\.(\B|\b[0-9]+)</string>
					<key>name</key>
					<string>invalid.illegal.numeric.octal.p4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?xi)
  (?:\B[-+])?
  (?:
    \b0b[0-1]*|                 # binary
    \b0o[0-7]*|                 # octal
    \b0x[0-9a-f]*|              # hex
    (
      \B\.[0-9]+|               # e.g. .123
      \b[0-9]+(\.[0-9]*)?       # e.g. 123.123, 123. or 123
    )(e[-+]?[0-9]+)?            # e.g. e+123, E-123
  (\s|;)                          # e.g. To avoid 234ABC
  )</string>
					<key>name</key>
					<string>constant.numeric.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-match-type-keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(exact|ternary|lpm|range|valid)\b</string>
					<key>name</key>
					<string>keyword.match.type.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-object-attribute-keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
# Tables / Header Types/ FieldList Calculation/ Calculated Fields
\b(reads|actions|min_size|max_size|size
  |fields|length|max_length
  |input|algorithm|output_width
  |verify|update
  |type|direct|static
  |instance_count|min_width|saturating)
\b</string>
					<key>name</key>
					<string>keyword.object.attribute.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-object-keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
\b(parser|table|action
  |header_type|header|metadata
  |field_list|field_list_calculation|calculated_field
  |control
  |parser_value_set)
\b</string>
					<key>name</key>
					<string>keyword.object.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-preprocessor-lex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lex-continuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lex-newline</string>
				</dict>
			</array>
		</dict>
		<key>p4-preprocessors</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#define-directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include-header-directive</string>
				</dict>
			</array>
		</dict>
		<key>p4-primitives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
\b(add_header|copy_header|remove_header
  |modify_field|add_to_field|subtract_from_field
  |add|subtract
  |set_field_to_hash_index
  |modify_field_with_hash_based_offset
  |modify_field_rng_uniform
  |truncate|drop|no_op
  |push|pop
  |count
  |execute_meter
  |generate_digest
  |resubmit|recirculate
  |clone_ingress_pkt_to_ingress
  |clone_egress_pkt_to_ingress
  |clone_ingress_pkt_to_egress
  |clone_egress_pkt_to_egress
  |bit_and|bit_or|bit_xor
  |shift_right|shift_left
  |register_read
  |register_write)
\b</string>
					<key>name</key>
					<string>keyword.primitives.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-stateful</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(counter|meter|register)\b</string>
					<key>name</key>
					<string>storage.stateful.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>return</string>
					<key>name</key>
					<string>keyword.statement.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-todo</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(contained|FIXME|TODO|ToDo|todo)\b</string>
					<key>name</key>
					<string>keyword.todo.p4</string>
				</dict>
			</array>
		</dict>
		<key>p4-translation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#p4-comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-preprocessors</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-abstractions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#p4-literal-number</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.p4</string>
	<key>uuid</key>
	<string>1a864ad6-0f6b-485e-9b73-245db18e4852</string>
</dict>
</plist>
